name: Build

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: spring-io/spring-gradle-build-action@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew build --continue
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ secrets.ARTIFACTORY_USERNAME != null && secrets.ARTIFACTORY_PASSWORD != null }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: spring-io/spring-gradle-build-action@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Deploy artifacts
        run: ./gradlew publishArtifacts finalizeDeployArtifacts --stacktrace -PartifactoryUsername="$ARTIFACTORY_USERNAME" -PartifactoryPassword="$ARTIFACTORY_PASSWORD"
